apiVersion: v1
kind: Service
metadata:
  name: sku-vanilla-app
  labels:
    app: sku-vanilla-app
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: sku-vanilla-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sku-vanilla-app
  labels:
    app: sku-vanilla-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sku-vanilla-app
  template:
    metadata:
      labels:
        app: sku-vanilla-app
    spec:
      containers:
      - name: sku-vanilla-app
        # created with Skaffold+Kustomize
        image: sku-vanilla-app-image
        env:
        - name: APP_NAME
          value: A Wonderful App in NodeJS + Express
        - name: SPEAKER_NAME
          value: Guy K. Enderson # GKE
        - name: OCCASIONAL_MESSAGE
          value: |
            Nobody will remember:<br/>
            - Your salary<br/>
            - Your fancy title<br/>
            - How 'busy' you were<br/>
            - How stressed you were<br/>
            - How many hours you worked<br/>
            <br/>
            People will remember:<br/>
            - Your commit that cause a production issue<br/>
