# I want to experiment with a HYDRATED yaml (embedding project ids and such)
# just to see how it goes across multiple machines. I never do that, I just
# want to see the experience in my vanilla app.
#

apiVersion: skaffold/v3 # v2beta29
kind: Config
metadata:
  name: vanilla-app
# build:
#   artifacts:
#   - image:  vanilla-app
#     context: app
#     buildpacks:
#       builder: gcr.io/buildpacks/builder:v1
# common build for all
build:
  artifacts:
    # SKU stands for Skaffold + Kustomize
    - image: sku-vanilla-app-image
      context: app
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1

profiles:
  - name: dev
    deploy:
      # TODO(create with pulumi)
      # gcloud container clusters get-credentials cicd-canary --region us-central1 --project cicd-platinum-test031
      kubeContext: 'gke_cicd-platinum-test031_us-central1_cicd-dev'
    manifests:
      kustomize:
        paths: ["deploy/k8s/overlays/dev"]

  - name: cloudrun-test
    deploy:
      cloudrun:
        projectid: cicd-platinum-test032
        region: us-central1

  # #kube-context:
  - name: prod
    #activation:
    #kubectl:
    deploy:
      kubeContext: 'gke_cicd-platinum-test031_us-central1_cicd-prod'
    manifests:
      kustomize:
        paths: ["deploy/k8s/overlays/prod"]
