# I want to experiment with a HYDRATED yaml (embedding project ids and such)
# just to see how it goes across multiple machines. I never do that, I just
# want to see the experience in my vanilla app.
#

apiVersion: skaffold/v3 # v2beta29
kind: Config
metadata:
  name: vanilla-app-skaffold-configuration # just to make sure you dont confuse it.
# build:
#   artifacts:
#   - image:  vanilla-app
#     context: app
#     buildpacks:
#       builder: gcr.io/buildpacks/builder:v1
# common build for all
build:
  artifacts:
    # SKU stands for Skaffold + Kustomize
    - context: app
      #image: sku-vanilla-app-image
      image: us-central1-docker.pkg.dev/cicd-platinum-test031/my-skaffold-cornucopia/sku-vanilla-app-image
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
profiles:
  ########################################################################
  # $ skaffold dev -p dev
  # Used for development, deploys to a DEV GKE cluster.
  ########################################################################
  - name: dev
    deploy:
      # TODO(create with pulumi)
      # gcloud container clusters get-credentials cicd-canary --region us-central1 --project cicd-platinum-test031
      kubeContext: 'gke_cicd-platinum-test031_us-central1_cicd-dev'
    manifests:
      kustomize:
        paths: ["deploy/k8s/overlays/dev"]

<<<<<<< HEAD
  ########################################################################
  # $ skaffold dev -p wietse
  # Used to test deployment to Cloud Run
  ########################################################################
  - name: wietse # cloudrun-test
    manifests:
      rawYaml:
      - deploy/cloudrun/*.yaml
    deploy:
      #kube-context: gke_cicd-platinum-test031_us-central1_cicd-dev
      cloudrun:
        # TODO(pulumi): enable Cloud Run API here.
        projectid: cicd-platinum-test031
        region: asia-southeast2 # I love Jakarta even though i dont like Java :)
        # name is not here... but in the YAML.

  ########################################################################
  # $ skaffold dev -p prod
  # Used in prod, deploys to a PROD GKE cluster.
  ########################################################################
  - name: prod
    deploy:
      kubeContext: 'gke_cicd-platinum-test031_us-central1_cicd-prod'
    manifests:
      kustomize:
        paths: ["deploy/k8s/overlays/prod"]
=======
  - name: prod
    manifests:
      kustomize:
        paths: ["deploy/k8s/overlays/prod"]


  # inspired by Christoph https://github.com/cgrotz/blog-examples/blob/main/cloud-deploy-to-cloud-run/skaffold.yaml
  - name: cloudrun
    manifests:
      rawYaml:
      - deploy/cloudrun/run-service.yaml
    deploy:
      cloudrun:
        projectid: cicd-platinum-test032
        region: us-central1
        #allow-unauthenticated: true

>>>>>>> d707e3a (it works! CloudRun deployed!)
