apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: vanilla-app
build:
  artifacts:
  - image:  vanilla-app2
    context: app2
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    #- app2/deployment.yaml
    - deploy/k8s/*.yaml
