apiVersion: v1
kind: Service
metadata:
  name: vanilla-app
  labels:
    app: vanilla-app
# spec:
#   clusterIP: None
#   selector:
#     app: vanilla-app
spec:
  ports:
  - port: 8080
    protocol: TCP
  #clusterIP: None
  type: LoadBalancer
  selector:
    app: vanilla-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanilla-app
  labels:
    app: vanilla-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanilla-app
  template:
    metadata:
      labels:
        app: vanilla-app
    spec:
      containers:
      - name: vanilla-app
        image: vanilla-app
