install:
	npm install
	npm i dotenv
	npm i sass
	npm i dotenv-expand

run:
	npm run scss-riccardo-once
	DEBUG=myapp:* OCCASIONAL_MESSAGE='Running in debug from Makefile' DEPLOY_TARGET='Makefile' LAUNCHING_HOSTNAME=`hostname` npm start
