# copied from https://github.com/palladius/clouddeploy-platinum-path/blob/main/apps/app03/k8s/overlays/production/kustomization.yaml
#####################################################
# PROD: Add replicas and add ENV for Cloud Deploy :)
#####################################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vanilla-prod
resources:
  - ../../base
  - namespace.yaml
replicas:
  - name: sku-vanilla-app
    # In prod we need more capacity :)
    count: 3
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: DEPLOY_TARGET
        value: "Prod (Production)"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: FAVORITE_COLOR
        value: "WHITE"
  target:
    kind: Deployment
    name: sku-vanilla-app
