apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vanilla-dev
resources:
  - ../../base
  - namespace.yaml
#components:
#  - ../../../../../components/common/dev




# inspired by https://github.com/palladius/clouddeploy-platinum-path/blob/main/apps/app03/k8s/overlays/dev/kustomization.yaml


# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# namespace: cicd-dev
# resources:
#   - ../../base
#   - namespace.yaml
# components:
#   - ../../../../../components/common/dev
# patches:
# - patch: |-
#     - op: add
#       path: "/spec/template/spec/containers/0/env/-"
#       value:
#         name: CLOUD_DEPLOY_TARGET #RICCARDO_KUSTOMIZE_ENV
#         value: "01 Dev (Development)"
#     # - op: add
#     #   path: "/spec/template/spec/containers/0/env/-"
#     #   value:
#     #     name: FAVORITE_COLOR_DUPE
#     #     value: red
#   target:
#     kind: Deployment
#     name: app03-kunode
