#####################################################
# DEV: Add two ENV for Cloud Deploy :)
#####################################################
# inspired by https://github.com/palladius/clouddeploy-platinum-path/blob/main/apps/app03/k8s/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vanilla-dev
resources:
  - ../../base
  - namespace.yaml
# replicas:
#   - name: sku-vanilla-app
#     # In prod we need more capacity :)
#     count: 3
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: DEPLOY_TARGET
        value: "Dev (Development)"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: FAVORITE_COLOR
        value: "YELLOW"
  target:
    kind: Deployment
    name: sku-vanilla-app
